/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;

import javax.swing.JOptionPane;

/**
 *
 * @author Estudiante
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarInformacion
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    // <editor-fold defaultstate="collapsed" desc="Funciones">    
    private void mostrarDatosPropietarios() {
        String fichero = "";

        try {
            BufferedReader br = new BufferedReader(new FileReader("Propietarios_Apartamentos.json"));
            String linea;
            while ((linea = br.readLine()) != null) {
                fichero += linea;
            }

            if (!fichero.isEmpty()) {
                ListaPropietarios abrir = new ListaPropietarios();
                this.setVisible(false);
                abrir.setVisible(true);
            } else {
                JOptionPane.showConfirmDialog(null, "No se han registrado datos", "Precaución", JOptionPane.CLOSED_OPTION);
            }

        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error Fichero no encontrado", 0);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", 0);
        }
    }

    private void ingresarNuevoPropietario() {
        String fichero = "";

        try {
            BufferedReader br = new BufferedReader(new FileReader("Administracion.json"));
            String linea;
            while ((linea = br.readLine()) != null) {
                fichero += linea;
            }

            if (!fichero.isEmpty()) {
                NuevoPropietario abrir = new NuevoPropietario();
                this.setVisible(false);
                abrir.setVisible(true);
            } else {
                JOptionPane.showConfirmDialog(null, "Ingrese los datos de administracion", "Precaución", JOptionPane.CLOSED_OPTION);
            }

        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error Fichero no encontrado", 0);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", 0);
        }
    }

    private void pagarAdminApartamentos() {
        String fichero = "";

        try {
            BufferedReader br = new BufferedReader(new FileReader("Propietarios_Apartamentos.json"));
            String linea;
            while ((linea = br.readLine()) != null) {
                fichero += linea;
            }

            if (!fichero.isEmpty()) {
                PagarAdministracionApartamentos abrir = new PagarAdministracionApartamentos();
                this.setVisible(false);
                abrir.setVisible(true);
            } else {
                JOptionPane.showConfirmDialog(null, "No se han registrado datos", "Precaución", JOptionPane.CLOSED_OPTION);
            }

        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error Fichero no encontrado", 0);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", 0);
        }
    }

    private void pagarAdminCasas() {
        String fichero = "";

        try {
            BufferedReader br = new BufferedReader(new FileReader("Propietarios_Casas.json"));
            String linea;
            while ((linea = br.readLine()) != null) {
                fichero += linea;
            }

            if (!fichero.isEmpty()) {
                PagarAdministracionCasas abrir = new PagarAdministracionCasas();
                this.setVisible(false);
                abrir.setVisible(true);
            } else {
                JOptionPane.showConfirmDialog(null, "No se han registrado datos", "Precaución", JOptionPane.CLOSED_OPTION);
            }

        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error Fichero no encontrado", 0);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", 0);
        }
    }

    // </editor-fold> 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botonInfoPropietarios = new javax.swing.JButton();
        botonPagarAdministracion = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        botonNuevoPropietario = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        botonPagarCasa = new javax.swing.JButton();
        botonActualizarDatosAdministracion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("MENU ADMINISTRACION");

        botonInfoPropietarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ayuda.png"))); // NOI18N
        botonInfoPropietarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInfoPropietariosActionPerformed(evt);
            }
        });

        botonPagarAdministracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/money.png"))); // NOI18N
        botonPagarAdministracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPagarAdministracionActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Informacion propietarios");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Pagar administracion apartamento");

        botonNuevoPropietario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonNuevoPropietario.setText("Nuevo Propietario");
        botonNuevoPropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoPropietarioActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Pagar administracion casa");

        botonPagarCasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/money.png"))); // NOI18N
        botonPagarCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPagarCasaActionPerformed(evt);
            }
        });

        botonActualizarDatosAdministracion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonActualizarDatosAdministracion.setText("Actualizar Datos Administracion");
        botonActualizarDatosAdministracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarDatosAdministracionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(173, 173, 173))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonActualizarDatosAdministracion)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonNuevoPropietario)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonPagarAdministracion)
                            .addComponent(botonInfoPropietarios)
                            .addComponent(botonPagarCasa))
                        .addGap(80, 80, 80))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(70, 70, 70)
                .addComponent(botonActualizarDatosAdministracion)
                .addGap(50, 50, 50)
                .addComponent(botonNuevoPropietario)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(botonInfoPropietarios))
                                .addGap(50, 50, 50)
                                .addComponent(jLabel7))
                            .addComponent(botonPagarAdministracion))
                        .addGap(50, 50, 50)
                        .addComponent(jLabel8))
                    .addComponent(botonPagarCasa))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonInfoPropietariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInfoPropietariosActionPerformed
        mostrarDatosPropietarios();
    }//GEN-LAST:event_botonInfoPropietariosActionPerformed

    private void botonNuevoPropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoPropietarioActionPerformed
        ingresarNuevoPropietario();
    }//GEN-LAST:event_botonNuevoPropietarioActionPerformed

    private void botonPagarCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPagarCasaActionPerformed
        pagarAdminCasas();
    }//GEN-LAST:event_botonPagarCasaActionPerformed

    private void botonPagarAdministracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPagarAdministracionActionPerformed
        pagarAdminApartamentos();
    }//GEN-LAST:event_botonPagarAdministracionActionPerformed

    private void botonActualizarDatosAdministracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarDatosAdministracionActionPerformed
        ActualizarDatosAdministracion abrir = new ActualizarDatosAdministracion();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonActualizarDatosAdministracionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizarDatosAdministracion;
    private javax.swing.JButton botonInfoPropietarios;
    private javax.swing.JButton botonNuevoPropietario;
    private javax.swing.JButton botonPagarAdministracion;
    private javax.swing.JButton botonPagarCasa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
